### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by tillkruss** [wamiz/heroku-buildpack-igbinary#1]
Does this need to be added before or after the default PHP buildpack?

**Comment by potsky** [comment]
In a PHP application where assets are built with npm, we use this `app.json`:

```
{
    ...
    "buildpacks": [
        {
            "url": "heroku/nodejs"
        },
        {
            "url": "heroku/php"
        },
        {
            "url": "https://github.com/wamiz/heroku-buildpack-mysql"
        },
        {
            "url": "https://github.com/wamiz/heroku-buildpack-igbinary"
        }
    ]
    ...
}
```

**Comment by potsky** [comment]
It provides this configuration in the dashboard:

<img width="1223" alt="Screenshot 2021-02-28 at 17 25 38@2x" src="https://user-images.githubusercontent.com/408237/109425723-fe8e1f80-79e9-11eb-8e7c-de239538fe89.png">

**Comment by tillkruss** [comment]
After `heroku/php`, thanks 👍

**Comment by potsky** [comment]
@tillkruss do not hesitate to star this repo if you use it ;-)

**Comment by tillkruss** [comment]
@potsky: I'm currently experimenting with using a buildpack vs the `HEROKU_PHP_PLATFORM_REPOSITORIES` [approach](https://github.com/heroku/heroku-buildpack-php/blob/master/support/build/README.md#hosting-a-proprietary-extension-using-custom-tooling).

**Comment by tillkruss** [comment]
I went with the official route and published it here: https://github.com/cachewerk/heroku-php-extensions
